SELECT ?test ?result ?input ?req WHERE {
    ?test
        a $test_class ;
        mf:result ?result ;
        mf:action ?input .

    OPTIONAL {
        ?test jld:req ?req .
    }

    # FIXME: We mimic how `pyld` tests work, skipping 1.0 tests. This is probably incorrect though.
    FILTER NOT EXISTS {
        ?test jld:option / jld:specVersion "json-ld-1.0"^^xsd:string .
    }
}
