SELECT ?test ?result ?input ?req ?extract_all_scripts ?base ?context ?frame WHERE {
    ?test
        a $test_class ;
        mf:result ?result ;
        mf:action ?input .

    OPTIONAL {
        ?test jld:req ?req .
    }

    OPTIONAL {
        ?test jld:option / jld:extractAllScripts ?extract_all_scripts .
    }

    OPTIONAL {
        ?test jld:option / jld:base ?base .
    }

    OPTIONAL {
        ?test jld:context ?context .
    }

    OPTIONAL {
        ?test jld:frame ?frame .
    }

    # FIXME: We mimic how `pyld` tests work, skipping 1.0 tests. This is probably incorrect though.
    FILTER NOT EXISTS {
        ?test jld:option / jld:specVersion "json-ld-1.0"^^xsd:string .
    }

    FILTER NOT EXISTS {
        ?test jld:option / jld:processingMode "json-ld-1.0"^^xsd:string .
    }
}
