name: Unit tests

on: [pull_request]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Test
        shell: bash
        run: poetry run j ci
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Pytest coverage comment
        if: always()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: tests/artifacts/coverage.txt
          junitxml-path: tests/artifacts/pytest.xml

      - name: Post Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: pytest
          path: tests/artifacts/pytest.xml
          reporter: jest-junit

      - name: Upload pytest.xml
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: pytest-xml
          path: tests/artifacts/pytest.xml
